AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Recicly"

Globals:
  Function:
    CodeUri: "../recicly/"
    Runtime: "python3.7"
    MemorySize: 128
    Timeout: 60
    Environment:
      Variables:
        ENVIRONMENT: "production"
        REGION: !Ref AWS::Region
        ACCOUNT_ID: !Ref AWS::AccountId
        PASSWORD: "{{resolve:ssm:/recicly/rds/password:1}}"
        URL: "{{resolve:ssm:/recicly/rds/url:1}}"

Resources:
  # IAM
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-api-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "EventBus"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "events:PutEvents"
                Resource: "*"

  # API
  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: "Prod"

  # User
  GetAllUsers:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-users"
      Handler: "handlers.user.get_all.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /user/get-all
            Method: get

  GetUser:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-user"
      Handler: "handlers.user.get.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /user/get
            Method: get

  AddUser:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-add-user"
      Handler: "handlers.user.add.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /user/add
            Method: post

  UpdateUser:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-update-user"
      Handler: "handlers.user.update.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /user/update
            Method: put

  DeleteUser:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-delete-user"
      Handler: "handlers.user.delete.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /user/delete
            Method: delete

  # Driver
  GetAllDrivers:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-drivers"
      Handler: "handlers.driver.get_all.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /driver/get-all
            Method: get

  GetDriver:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-driver"
      Handler: "handlers.driver.get.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /driver/get
            Method: get

  AddDriver:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-add-driver"
      Handler: "handlers.driver.add.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /driver/add
            Method: post

  UpdateDriver:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-update-driver"
      Handler: "handlers.driver.update.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /driver/update
            Method: put

  DeleteDriver:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-delete-driver"
      Handler: "handlers.driver.delete.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /driver/delete
            Method: delete

  # Collector
  GetAllCollectors:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-collectors"
      Handler: "handlers.collector.get_all.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /collector/get-all
            Method: get

  GetCollector:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-collector"
      Handler: "handlers.collector.get.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /collector/get
            Method: get

  AddCollector:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-add-collector"
      Handler: "handlers.collector.add.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /collector/add
            Method: post

  UpdateCollector:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-update-collector"
      Handler: "handlers.collector.update.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /collector/update
            Method: put

  DeleteCollector:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-delete-collector"
      Handler: "handlers.collector.delete.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /collector/delete
            Method: delete

  # Car
  GetAllCars:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-cars"
      Handler: "handlers.car.get_all.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /car/get-all
            Method: get

  GetCar:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-car"
      Handler: "handlers.car.get.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /car/get
            Method: get

  AddCar:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-add-car"
      Handler: "handlers.car.add.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /car/add
            Method: post

  UpdateCar:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-update-car"
      Handler: "handlers.car.update.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /car/update
            Method: put

  DeleteCar:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-delete-car"
      Handler: "handlers.car.delete.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /car/delete
            Method: delete

  # Car
  GetAllPartners:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-partners"
      Handler: "handlers.partner.get_all.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /partner/get-all
            Method: get

  GetPartner:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-get-partner"
      Handler: "handlers.partner.get.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /partner/get
            Method: get

  AddPartner:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-add-partner"
      Handler: "handlers.partner.add.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /partner/add
            Method: post

  UpdatePartner:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-update-partner"
      Handler: "handlers.partner.update.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /partner/update
            Method: put

  DeletePartner:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AWS::StackName}-delete-partner"
      Handler: "handlers.partner.delete.handle"
      Role: !GetAtt ExecutionRole.Arn
      Events:
        ApiEnpoint:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /partner/delete
            Method: delete
